[package]
name = "pwnage_checker"
version = "1.0.0"
authors = ["Sebastian Magnusson <sebbe.magnusson@gmail.com>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"
sha1 = "0.10.6"
hex = "0.4.3"
